In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

#Deep learning
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1790203178.410978    2896 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1790203178.842273    2896 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1790203180.871495    2896 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [3]:
df=pd.read_csv("housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
df.shape

(20640, 10)

In [5]:
df.info

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]>

In [6]:
df.select_dtypes(include="object").columns

Index(['ocean_proximity'], dtype='object')

In [7]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [8]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [10]:
df["total_bedrooms"] = df["total_bedrooms"].fillna(
    df["total_bedrooms"].median()
)

In [11]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [12]:
OneHot_Encoder_ocean_proximity=OneHotEncoder(sparse_output=False)
encoded=OneHot_Encoder_ocean_proximity.fit_transform(df[['ocean_proximity']])


encoded_df = pd.DataFrame(
    encoded,
    columns=OneHot_Encoder_ocean_proximity.get_feature_names_out(
        ['ocean_proximity']
    ),
    index=df.index
)

df = pd.concat(
    [df.drop('ocean_proximity', axis=1), encoded_df],
    axis=1
)

In [13]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity_<1H OCEAN',
       'ocean_proximity_INLAND', 'ocean_proximity_ISLAND',
       'ocean_proximity_NEAR BAY', 'ocean_proximity_NEAR OCEAN'],
      dtype='object')

In [14]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0.0,1.0,0.0,0.0,0.0

In [15]:
X=df.drop("median_house_value",axis=1)
y=df['median_house_value']

In [16]:
X = np.array(X)
y = np.array(y)

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(X.shape)
print(y.shape)

(16512, 13)
(4128, 13)
(16512,)
(4128,)
(20640, 13)
(20640,)

In [19]:
#scaling 
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [20]:
X_train.shape[1]

13

In [21]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), 
    Dense(32,activation='relu'), 
    Dense(16,activation='relu'),
    Dense(1,activation='linear')#Linear for regression
])

/home/debmalyaa/anaconda3/envs/tensorflow-gpu/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1790203182.363723    2896 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3617 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(
    optimizer='rmsprop',
    loss='mse',
    metrics=['mae']
)

In [24]:
Early_Stopping=EarlyStopping(monitor='val_loss',mode='min',patience=50,restore_best_weights=True)

In [25]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),callbacks=[Early_Stopping],epochs=10,batch_size=50,verbose=1)

Epoch 1/10

I0000 00:00:1790203183.823633    3081 service.cc:153] XLA service 0x7ab028030ce0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1790203183.823676    3081 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 3050 6GB Laptop GPU, Compute Capability 8.6 (Driver: 13.4.0; Runtime: 12.9.0; Toolkit: 12.5.0; DNN: 9.26.0)
I0000 00:00:1790203183.840375    3081 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1790203183.946386    3081 cuda_dnn.cc:461] Loaded cuDNN version 92600
I0000 00:00:1790203183.955674    3081 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1044__.10
I0000 00:00:1790203183.963750    3081 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1790203184.865284    3081 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.

 80/331 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54262773350.4000 - mae: 202819.1289

I0000 00:00:1790203186.519281    3081 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

330/331 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55553048389.8182 - mae: 205655.8563

I0000 00:00:1790203187.224849    3082 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1044__.10

331/331 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 56120963072.0000 - mae: 206771.1875 - val_loss: 54613139456.0000 - val_mae: 203754.9219
Epoch 2/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53211738112.0000 - mae: 199635.7656 - val_loss: 48368250880.0000 - val_mae: 187996.2188
Epoch 3/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 41315266560.0000 - mae: 167241.3906 - val_loss: 30535014400.0000 - val_mae: 135031.0469
Epoch 4/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20403660800.0000 - mae: 104061.6328 - val_loss: 12071094272.0000 - val_mae: 83012.7656
Epoch 5/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11399603200.0000 - mae: 84108.2891 - val_loss: 10563240960.0000 - val_mae: 81229.2031
Epoch 6/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10320228352.0000 - mae: 80447.9453 - val_loss: 9648960512.0000 - val_mae: 77118.6484
Epoch 7/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9485576192.0000 - mae: 76681.0547 - val_loss: 8906683392.0000 - val_mae: 73967.0938
Epoch 8/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8839699456.0000 - mae: 73478.6406 - val_loss: 8371359232.0000 - val_mae: 71119.5000
Epoch 9/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8369272832.0000 - mae: 70891.5938 - val_loss: 7990899200.0000 - val_mae: 68502.8516
Epoch 10/10
331/331 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8024569344.0000 - mae: 68942.1094 - val_loss: 7698862080.0000 - val_mae: 67061.0938

In [27]:
import pickle

with open("ocean_proximity_encoder.pkl", "wb") as file:
    pickle.dump(OneHot_Encoder_ocean_proximity, file)
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler,file)

In [28]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [29]:
model.save("model.keras")

In [30]:
##accuracy
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
MAE : 67061.09154327156
MSE : 7698861943.8028345
RMSE: 87743.15895728188
R² Score: 0.412484035775012